imageWidth      : 1280
imageHeight     : 720

goldenDataset   : '/home/jmv/data/mlproj10/LeryPosesGolden/dataset'
datasetDir      : '/home/jmv/data/mlproj10/dataset'
tmpDir          : 'tmp'
trnDir          : 'trn' 
valDir          : 'val' 
tstDir          : 'tst'
remDir          : 'rem' 

nTrnSamples     : 2000
nValSamples     : 671
nTstSamples     : 671

nEpochs         : 1000 
batchSize       : 16
learningRate    : 1e-6 

checkpointDir   : '/home/jmv/data/mlproj10/tmp/'
logDir          : '/home/jmv/data/mlproj10/log/'

createDataset   : True
checkDataset    : True

# Possible values for variable classification: 'binary' or 'categorical'
classification  : 'binary'
