imageWidth      : 1280
imageHeight     : 720

tmpDir          : '/home/jmv/data/mlproj10/dataset/tmp'
trnDir          : '/home/jmv/data/mlproj10/dataset/trn' 
valDir          : '/home/jmv/data/mlproj10/dataset/val' 
tstDir          : '/home/jmv/data/mlproj10/dataset/tst'
remDir          : '/home/jmv/data/mlproj10/dataset/rem' 

nTrnSamples     : 2000
nValSamples     : 671
nTstSamples     : 671

nEpochs         : 1000 
batchSize       : 16
learningRate    : 1e-6 

checkpointDir   : '/home/jmv/data/mlproj10/tmp/'
logDir          : '/home/jmv/data/mlproj10/log/'

createDataset   : True
checkDataset    : True
