imageWidth      : 768
imageHeight     : 500

goldenDataset   : '/home/jmv/data/mlproj11/SignifyGolden20191212/dataset'

# The application assumes that that trnDir, valDir & tstDir are folders under datasetDir
datasetDir      : '/home/jmv/data/mlproj11/dataset'
trnDir          : '/home/jmv/data/mlproj11/dataset/trn' 
valDir          : '/home/jmv/data/mlproj11/dataset/val' 
tstDir          : '/home/jmv/data/mlproj11/dataset/tst'

nEpochs         : 1000 
batchSize       : 8
learningRate    : 1e-3

checkpointDir   : '/home/jmv/data/mlproj11/tmp/'
logDir          : '/home/jmv/data/mlproj11/log/'

createDataset   : True
checkDataset    : True
